/**
 * generated by Xtext 2.20.0
 */
package de.tu_dortmund.mGPL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Decl</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.tu_dortmund.mGPL.MGPLPackage#getDecl()
 * @model
 * @generated
 */
public interface Decl extends ReferenceTarget
{
} // Decl
