/**
 * generated by Xtext 2.20.0
 */
package de.tu_dortmund.mGPL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.tu_dortmund.mGPL.MGPLPackage#getExpr()
 * @model
 * @generated
 */
public interface Expr extends EObject
{
} // Expr
