/**
 * generated by Xtext 2.20.0
 */
package de.tu_dortmund.mGPL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see de.tu_dortmund.mGPL.MGPLFactory
 * @model kind="package"
 * @generated
 */
public interface MGPLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "mGPL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.tu_dortmund.de/MGPL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "mGPL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MGPLPackage eINSTANCE = de.tu_dortmund.mGPL.impl.MGPLPackageImpl.init();

  /**
   * The meta object id for the '{@link de.tu_dortmund.mGPL.impl.ReferenceTargetImpl <em>Reference Target</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.tu_dortmund.mGPL.impl.ReferenceTargetImpl
   * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getReferenceTarget()
   * @generated
   */
  int REFERENCE_TARGET = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCE_TARGET__NAME = 0;

  /**
   * The number of structural features of the '<em>Reference Target</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCE_TARGET_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.tu_dortmund.mGPL.impl.ProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.tu_dortmund.mGPL.impl.ProgramImpl
   * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getProgram()
   * @generated
   */
  int PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__NAME = REFERENCE_TARGET__NAME;

  /**
   * The feature id for the '<em><b>Attributes</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__ATTRIBUTES = REFERENCE_TARGET_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Declarations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__DECLARATIONS = REFERENCE_TARGET_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Init</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__INIT = REFERENCE_TARGET_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Blocks</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__BLOCKS = REFERENCE_TARGET_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_FEATURE_COUNT = REFERENCE_TARGET_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link de.tu_dortmund.mGPL.impl.DeclImpl <em>Decl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.tu_dortmund.mGPL.impl.DeclImpl
   * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getDecl()
   * @generated
   */
  int DECL = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECL__NAME = REFERENCE_TARGET__NAME;

  /**
   * The number of structural features of the '<em>Decl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECL_FEATURE_COUNT = REFERENCE_TARGET_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link de.tu_dortmund.mGPL.impl.VarDeclImpl <em>Var Decl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.tu_dortmund.mGPL.impl.VarDeclImpl
   * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getVarDecl()
   * @generated
   */
  int VAR_DECL = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_DECL__NAME = DECL__NAME;

  /**
   * The number of structural features of the '<em>Var Decl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_DECL_FEATURE_COUNT = DECL_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link de.tu_dortmund.mGPL.impl.ScalarVarDeclImpl <em>Scalar Var Decl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.tu_dortmund.mGPL.impl.ScalarVarDeclImpl
   * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getScalarVarDecl()
   * @generated
   */
  int SCALAR_VAR_DECL = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCALAR_VAR_DECL__NAME = VAR_DECL__NAME;

  /**
   * The feature id for the '<em><b>Initialization</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCALAR_VAR_DECL__INITIALIZATION = VAR_DECL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Scalar Var Decl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCALAR_VAR_DECL_FEATURE_COUNT = VAR_DECL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link de.tu_dortmund.mGPL.impl.ArrayVarDeclImpl <em>Array Var Decl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.tu_dortmund.mGPL.impl.ArrayVarDeclImpl
   * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getArrayVarDecl()
   * @generated
   */
  int ARRAY_VAR_DECL = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_VAR_DECL__NAME = VAR_DECL__NAME;

  /**
   * The feature id for the '<em><b>Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_VAR_DECL__SIZE = VAR_DECL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Array Var Decl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_VAR_DECL_FEATURE_COUNT = VAR_DECL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link de.tu_dortmund.mGPL.impl.ObjDeclImpl <em>Obj Decl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.tu_dortmund.mGPL.impl.ObjDeclImpl
   * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getObjDecl()
   * @generated
   */
  int OBJ_DECL = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJ_DECL__NAME = DECL__NAME;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJ_DECL__TYPE = DECL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Attributes</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJ_DECL__ATTRIBUTES = DECL_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Obj Decl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJ_DECL_FEATURE_COUNT = DECL_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link de.tu_dortmund.mGPL.impl.ObjArrayDeclImpl <em>Obj Array Decl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.tu_dortmund.mGPL.impl.ObjArrayDeclImpl
   * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getObjArrayDecl()
   * @generated
   */
  int OBJ_ARRAY_DECL = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJ_ARRAY_DECL__NAME = DECL__NAME;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJ_ARRAY_DECL__TYPE = DECL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJ_ARRAY_DECL__SIZE = DECL_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Obj Array Decl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJ_ARRAY_DECL_FEATURE_COUNT = DECL_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link de.tu_dortmund.mGPL.impl.AttrAssListImpl <em>Attr Ass List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.tu_dortmund.mGPL.impl.AttrAssListImpl
   * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getAttrAssList()
   * @generated
   */
  int ATTR_ASS_LIST = 8;

  /**
   * The feature id for the '<em><b>Assignments</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTR_ASS_LIST__ASSIGNMENTS = 0;

  /**
   * The number of structural features of the '<em>Attr Ass List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTR_ASS_LIST_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.tu_dortmund.mGPL.impl.AttrAssImpl <em>Attr Ass</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.tu_dortmund.mGPL.impl.AttrAssImpl
   * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getAttrAss()
   * @generated
   */
  int ATTR_ASS = 9;

  /**
   * The feature id for the '<em><b>Attribute Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTR_ASS__ATTRIBUTE_NAME = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTR_ASS__VALUE = 1;

  /**
   * The number of structural features of the '<em>Attr Ass</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTR_ASS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link de.tu_dortmund.mGPL.impl.BlockImpl <em>Block</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.tu_dortmund.mGPL.impl.BlockImpl
   * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getBlock()
   * @generated
   */
  int BLOCK = 10;

  /**
   * The feature id for the '<em><b>Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOCK__ACTION = 0;

  /**
   * The number of structural features of the '<em>Block</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOCK_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.tu_dortmund.mGPL.impl.AnimBlockImpl <em>Anim Block</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.tu_dortmund.mGPL.impl.AnimBlockImpl
   * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getAnimBlock()
   * @generated
   */
  int ANIM_BLOCK = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANIM_BLOCK__NAME = REFERENCE_TARGET__NAME;

  /**
   * The feature id for the '<em><b>Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANIM_BLOCK__ACTION = REFERENCE_TARGET_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Target</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANIM_BLOCK__TARGET = REFERENCE_TARGET_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Anim Block</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANIM_BLOCK_FEATURE_COUNT = REFERENCE_TARGET_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link de.tu_dortmund.mGPL.impl.AnimTargetImpl <em>Anim Target</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.tu_dortmund.mGPL.impl.AnimTargetImpl
   * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getAnimTarget()
   * @generated
   */
  int ANIM_TARGET = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANIM_TARGET__NAME = REFERENCE_TARGET__NAME;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANIM_TARGET__TYPE = REFERENCE_TARGET_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Anim Target</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANIM_TARGET_FEATURE_COUNT = REFERENCE_TARGET_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link de.tu_dortmund.mGPL.impl.EventBlockImpl <em>Event Block</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.tu_dortmund.mGPL.impl.EventBlockImpl
   * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getEventBlock()
   * @generated
   */
  int EVENT_BLOCK = 13;

  /**
   * The feature id for the '<em><b>Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_BLOCK__ACTION = BLOCK__ACTION;

  /**
   * The feature id for the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_BLOCK__KEY = BLOCK_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Event Block</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_BLOCK_FEATURE_COUNT = BLOCK_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link de.tu_dortmund.mGPL.impl.StmtBlockImpl <em>Stmt Block</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.tu_dortmund.mGPL.impl.StmtBlockImpl
   * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getStmtBlock()
   * @generated
   */
  int STMT_BLOCK = 14;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STMT_BLOCK__STATEMENTS = 0;

  /**
   * The number of structural features of the '<em>Stmt Block</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STMT_BLOCK_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.tu_dortmund.mGPL.impl.StmtImpl <em>Stmt</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.tu_dortmund.mGPL.impl.StmtImpl
   * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getStmt()
   * @generated
   */
  int STMT = 15;

  /**
   * The number of structural features of the '<em>Stmt</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STMT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link de.tu_dortmund.mGPL.impl.IfStmtImpl <em>If Stmt</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.tu_dortmund.mGPL.impl.IfStmtImpl
   * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getIfStmt()
   * @generated
   */
  int IF_STMT = 16;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_STMT__CONDITION = STMT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Then</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_STMT__THEN = STMT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Else</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_STMT__ELSE = STMT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>If Stmt</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_STMT_FEATURE_COUNT = STMT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link de.tu_dortmund.mGPL.impl.ForStmtImpl <em>For Stmt</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.tu_dortmund.mGPL.impl.ForStmtImpl
   * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getForStmt()
   * @generated
   */
  int FOR_STMT = 17;

  /**
   * The feature id for the '<em><b>Init</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_STMT__INIT = STMT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_STMT__CONDITION = STMT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Step</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_STMT__STEP = STMT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_STMT__BODY = STMT_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>For Stmt</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_STMT_FEATURE_COUNT = STMT_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link de.tu_dortmund.mGPL.impl.AssStmtImpl <em>Ass Stmt</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.tu_dortmund.mGPL.impl.AssStmtImpl
   * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getAssStmt()
   * @generated
   */
  int ASS_STMT = 19;

  /**
   * The number of structural features of the '<em>Ass Stmt</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASS_STMT_FEATURE_COUNT = STMT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link de.tu_dortmund.mGPL.impl.AssignmentImpl <em>Assignment</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.tu_dortmund.mGPL.impl.AssignmentImpl
   * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getAssignment()
   * @generated
   */
  int ASSIGNMENT = 18;

  /**
   * The feature id for the '<em><b>Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGNMENT__VAR = ASS_STMT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGNMENT__VALUE = ASS_STMT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Assignment</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGNMENT_FEATURE_COUNT = ASS_STMT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link de.tu_dortmund.mGPL.impl.VarImpl <em>Var</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.tu_dortmund.mGPL.impl.VarImpl
   * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getVar()
   * @generated
   */
  int VAR = 20;

  /**
   * The feature id for the '<em><b>Variable</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR__VARIABLE = 0;

  /**
   * The feature id for the '<em><b>Index</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR__INDEX = 1;

  /**
   * The feature id for the '<em><b>Attribute</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR__ATTRIBUTE = 2;

  /**
   * The number of structural features of the '<em>Var</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link de.tu_dortmund.mGPL.impl.ExprImpl <em>Expr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.tu_dortmund.mGPL.impl.ExprImpl
   * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getExpr()
   * @generated
   */
  int EXPR = 21;

  /**
   * The number of structural features of the '<em>Expr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link de.tu_dortmund.mGPL.impl.UnaryExprImpl <em>Unary Expr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.tu_dortmund.mGPL.impl.UnaryExprImpl
   * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getUnaryExpr()
   * @generated
   */
  int UNARY_EXPR = 22;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNARY_EXPR__OP = EXPR_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operand</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNARY_EXPR__OPERAND = EXPR_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Unary Expr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNARY_EXPR_FEATURE_COUNT = EXPR_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link de.tu_dortmund.mGPL.impl.NumberExprImpl <em>Number Expr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.tu_dortmund.mGPL.impl.NumberExprImpl
   * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getNumberExpr()
   * @generated
   */
  int NUMBER_EXPR = 23;

  /**
   * The feature id for the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER_EXPR__NUMBER = EXPR_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Number Expr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER_EXPR_FEATURE_COUNT = EXPR_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link de.tu_dortmund.mGPL.impl.VarExprImpl <em>Var Expr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.tu_dortmund.mGPL.impl.VarExprImpl
   * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getVarExpr()
   * @generated
   */
  int VAR_EXPR = 24;

  /**
   * The feature id for the '<em><b>Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_EXPR__VAR = EXPR_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Var Expr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_EXPR_FEATURE_COUNT = EXPR_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link de.tu_dortmund.mGPL.impl.BinaryExprImpl <em>Binary Expr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.tu_dortmund.mGPL.impl.BinaryExprImpl
   * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getBinaryExpr()
   * @generated
   */
  int BINARY_EXPR = 25;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINARY_EXPR__LEFT = EXPR_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINARY_EXPR__OP = EXPR_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINARY_EXPR__RIGHT = EXPR_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Binary Expr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINARY_EXPR_FEATURE_COUNT = EXPR_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link de.tu_dortmund.mGPL.impl.TouchExprImpl <em>Touch Expr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.tu_dortmund.mGPL.impl.TouchExprImpl
   * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getTouchExpr()
   * @generated
   */
  int TOUCH_EXPR = 26;

  /**
   * The feature id for the '<em><b>Toucher</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOUCH_EXPR__TOUCHER = EXPR_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Touchee</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOUCH_EXPR__TOUCHEE = EXPR_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Touch Expr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOUCH_EXPR_FEATURE_COUNT = EXPR_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link de.tu_dortmund.mGPL.ObjType <em>Obj Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.tu_dortmund.mGPL.ObjType
   * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getObjType()
   * @generated
   */
  int OBJ_TYPE = 27;

  /**
   * The meta object id for the '{@link de.tu_dortmund.mGPL.KeyStroke <em>Key Stroke</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.tu_dortmund.mGPL.KeyStroke
   * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getKeyStroke()
   * @generated
   */
  int KEY_STROKE = 28;


  /**
   * Returns the meta object for class '{@link de.tu_dortmund.mGPL.Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see de.tu_dortmund.mGPL.Program
   * @generated
   */
  EClass getProgram();

  /**
   * Returns the meta object for the containment reference '{@link de.tu_dortmund.mGPL.Program#getAttributes <em>Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Attributes</em>'.
   * @see de.tu_dortmund.mGPL.Program#getAttributes()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Attributes();

  /**
   * Returns the meta object for the containment reference list '{@link de.tu_dortmund.mGPL.Program#getDeclarations <em>Declarations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Declarations</em>'.
   * @see de.tu_dortmund.mGPL.Program#getDeclarations()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Declarations();

  /**
   * Returns the meta object for the containment reference '{@link de.tu_dortmund.mGPL.Program#getInit <em>Init</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Init</em>'.
   * @see de.tu_dortmund.mGPL.Program#getInit()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Init();

  /**
   * Returns the meta object for the containment reference list '{@link de.tu_dortmund.mGPL.Program#getBlocks <em>Blocks</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Blocks</em>'.
   * @see de.tu_dortmund.mGPL.Program#getBlocks()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Blocks();

  /**
   * Returns the meta object for class '{@link de.tu_dortmund.mGPL.ReferenceTarget <em>Reference Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Reference Target</em>'.
   * @see de.tu_dortmund.mGPL.ReferenceTarget
   * @generated
   */
  EClass getReferenceTarget();

  /**
   * Returns the meta object for the attribute '{@link de.tu_dortmund.mGPL.ReferenceTarget#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see de.tu_dortmund.mGPL.ReferenceTarget#getName()
   * @see #getReferenceTarget()
   * @generated
   */
  EAttribute getReferenceTarget_Name();

  /**
   * Returns the meta object for class '{@link de.tu_dortmund.mGPL.Decl <em>Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Decl</em>'.
   * @see de.tu_dortmund.mGPL.Decl
   * @generated
   */
  EClass getDecl();

  /**
   * Returns the meta object for class '{@link de.tu_dortmund.mGPL.VarDecl <em>Var Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Var Decl</em>'.
   * @see de.tu_dortmund.mGPL.VarDecl
   * @generated
   */
  EClass getVarDecl();

  /**
   * Returns the meta object for class '{@link de.tu_dortmund.mGPL.ScalarVarDecl <em>Scalar Var Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Scalar Var Decl</em>'.
   * @see de.tu_dortmund.mGPL.ScalarVarDecl
   * @generated
   */
  EClass getScalarVarDecl();

  /**
   * Returns the meta object for the containment reference '{@link de.tu_dortmund.mGPL.ScalarVarDecl#getInitialization <em>Initialization</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Initialization</em>'.
   * @see de.tu_dortmund.mGPL.ScalarVarDecl#getInitialization()
   * @see #getScalarVarDecl()
   * @generated
   */
  EReference getScalarVarDecl_Initialization();

  /**
   * Returns the meta object for class '{@link de.tu_dortmund.mGPL.ArrayVarDecl <em>Array Var Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Array Var Decl</em>'.
   * @see de.tu_dortmund.mGPL.ArrayVarDecl
   * @generated
   */
  EClass getArrayVarDecl();

  /**
   * Returns the meta object for the attribute '{@link de.tu_dortmund.mGPL.ArrayVarDecl#getSize <em>Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Size</em>'.
   * @see de.tu_dortmund.mGPL.ArrayVarDecl#getSize()
   * @see #getArrayVarDecl()
   * @generated
   */
  EAttribute getArrayVarDecl_Size();

  /**
   * Returns the meta object for class '{@link de.tu_dortmund.mGPL.ObjDecl <em>Obj Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Obj Decl</em>'.
   * @see de.tu_dortmund.mGPL.ObjDecl
   * @generated
   */
  EClass getObjDecl();

  /**
   * Returns the meta object for the attribute '{@link de.tu_dortmund.mGPL.ObjDecl#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see de.tu_dortmund.mGPL.ObjDecl#getType()
   * @see #getObjDecl()
   * @generated
   */
  EAttribute getObjDecl_Type();

  /**
   * Returns the meta object for the containment reference '{@link de.tu_dortmund.mGPL.ObjDecl#getAttributes <em>Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Attributes</em>'.
   * @see de.tu_dortmund.mGPL.ObjDecl#getAttributes()
   * @see #getObjDecl()
   * @generated
   */
  EReference getObjDecl_Attributes();

  /**
   * Returns the meta object for class '{@link de.tu_dortmund.mGPL.ObjArrayDecl <em>Obj Array Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Obj Array Decl</em>'.
   * @see de.tu_dortmund.mGPL.ObjArrayDecl
   * @generated
   */
  EClass getObjArrayDecl();

  /**
   * Returns the meta object for the attribute '{@link de.tu_dortmund.mGPL.ObjArrayDecl#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see de.tu_dortmund.mGPL.ObjArrayDecl#getType()
   * @see #getObjArrayDecl()
   * @generated
   */
  EAttribute getObjArrayDecl_Type();

  /**
   * Returns the meta object for the attribute '{@link de.tu_dortmund.mGPL.ObjArrayDecl#getSize <em>Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Size</em>'.
   * @see de.tu_dortmund.mGPL.ObjArrayDecl#getSize()
   * @see #getObjArrayDecl()
   * @generated
   */
  EAttribute getObjArrayDecl_Size();

  /**
   * Returns the meta object for class '{@link de.tu_dortmund.mGPL.AttrAssList <em>Attr Ass List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attr Ass List</em>'.
   * @see de.tu_dortmund.mGPL.AttrAssList
   * @generated
   */
  EClass getAttrAssList();

  /**
   * Returns the meta object for the containment reference list '{@link de.tu_dortmund.mGPL.AttrAssList#getAssignments <em>Assignments</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Assignments</em>'.
   * @see de.tu_dortmund.mGPL.AttrAssList#getAssignments()
   * @see #getAttrAssList()
   * @generated
   */
  EReference getAttrAssList_Assignments();

  /**
   * Returns the meta object for class '{@link de.tu_dortmund.mGPL.AttrAss <em>Attr Ass</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attr Ass</em>'.
   * @see de.tu_dortmund.mGPL.AttrAss
   * @generated
   */
  EClass getAttrAss();

  /**
   * Returns the meta object for the attribute '{@link de.tu_dortmund.mGPL.AttrAss#getAttributeName <em>Attribute Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Attribute Name</em>'.
   * @see de.tu_dortmund.mGPL.AttrAss#getAttributeName()
   * @see #getAttrAss()
   * @generated
   */
  EAttribute getAttrAss_AttributeName();

  /**
   * Returns the meta object for the containment reference '{@link de.tu_dortmund.mGPL.AttrAss#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see de.tu_dortmund.mGPL.AttrAss#getValue()
   * @see #getAttrAss()
   * @generated
   */
  EReference getAttrAss_Value();

  /**
   * Returns the meta object for class '{@link de.tu_dortmund.mGPL.Block <em>Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Block</em>'.
   * @see de.tu_dortmund.mGPL.Block
   * @generated
   */
  EClass getBlock();

  /**
   * Returns the meta object for the containment reference '{@link de.tu_dortmund.mGPL.Block#getAction <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Action</em>'.
   * @see de.tu_dortmund.mGPL.Block#getAction()
   * @see #getBlock()
   * @generated
   */
  EReference getBlock_Action();

  /**
   * Returns the meta object for class '{@link de.tu_dortmund.mGPL.AnimBlock <em>Anim Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Anim Block</em>'.
   * @see de.tu_dortmund.mGPL.AnimBlock
   * @generated
   */
  EClass getAnimBlock();

  /**
   * Returns the meta object for the containment reference '{@link de.tu_dortmund.mGPL.AnimBlock#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Target</em>'.
   * @see de.tu_dortmund.mGPL.AnimBlock#getTarget()
   * @see #getAnimBlock()
   * @generated
   */
  EReference getAnimBlock_Target();

  /**
   * Returns the meta object for class '{@link de.tu_dortmund.mGPL.AnimTarget <em>Anim Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Anim Target</em>'.
   * @see de.tu_dortmund.mGPL.AnimTarget
   * @generated
   */
  EClass getAnimTarget();

  /**
   * Returns the meta object for the attribute '{@link de.tu_dortmund.mGPL.AnimTarget#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see de.tu_dortmund.mGPL.AnimTarget#getType()
   * @see #getAnimTarget()
   * @generated
   */
  EAttribute getAnimTarget_Type();

  /**
   * Returns the meta object for class '{@link de.tu_dortmund.mGPL.EventBlock <em>Event Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Event Block</em>'.
   * @see de.tu_dortmund.mGPL.EventBlock
   * @generated
   */
  EClass getEventBlock();

  /**
   * Returns the meta object for the attribute '{@link de.tu_dortmund.mGPL.EventBlock#getKey <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Key</em>'.
   * @see de.tu_dortmund.mGPL.EventBlock#getKey()
   * @see #getEventBlock()
   * @generated
   */
  EAttribute getEventBlock_Key();

  /**
   * Returns the meta object for class '{@link de.tu_dortmund.mGPL.StmtBlock <em>Stmt Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Stmt Block</em>'.
   * @see de.tu_dortmund.mGPL.StmtBlock
   * @generated
   */
  EClass getStmtBlock();

  /**
   * Returns the meta object for the containment reference list '{@link de.tu_dortmund.mGPL.StmtBlock#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see de.tu_dortmund.mGPL.StmtBlock#getStatements()
   * @see #getStmtBlock()
   * @generated
   */
  EReference getStmtBlock_Statements();

  /**
   * Returns the meta object for class '{@link de.tu_dortmund.mGPL.Stmt <em>Stmt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Stmt</em>'.
   * @see de.tu_dortmund.mGPL.Stmt
   * @generated
   */
  EClass getStmt();

  /**
   * Returns the meta object for class '{@link de.tu_dortmund.mGPL.IfStmt <em>If Stmt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>If Stmt</em>'.
   * @see de.tu_dortmund.mGPL.IfStmt
   * @generated
   */
  EClass getIfStmt();

  /**
   * Returns the meta object for the containment reference '{@link de.tu_dortmund.mGPL.IfStmt#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see de.tu_dortmund.mGPL.IfStmt#getCondition()
   * @see #getIfStmt()
   * @generated
   */
  EReference getIfStmt_Condition();

  /**
   * Returns the meta object for the containment reference '{@link de.tu_dortmund.mGPL.IfStmt#getThen <em>Then</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Then</em>'.
   * @see de.tu_dortmund.mGPL.IfStmt#getThen()
   * @see #getIfStmt()
   * @generated
   */
  EReference getIfStmt_Then();

  /**
   * Returns the meta object for the containment reference '{@link de.tu_dortmund.mGPL.IfStmt#getElse <em>Else</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Else</em>'.
   * @see de.tu_dortmund.mGPL.IfStmt#getElse()
   * @see #getIfStmt()
   * @generated
   */
  EReference getIfStmt_Else();

  /**
   * Returns the meta object for class '{@link de.tu_dortmund.mGPL.ForStmt <em>For Stmt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>For Stmt</em>'.
   * @see de.tu_dortmund.mGPL.ForStmt
   * @generated
   */
  EClass getForStmt();

  /**
   * Returns the meta object for the containment reference '{@link de.tu_dortmund.mGPL.ForStmt#getInit <em>Init</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Init</em>'.
   * @see de.tu_dortmund.mGPL.ForStmt#getInit()
   * @see #getForStmt()
   * @generated
   */
  EReference getForStmt_Init();

  /**
   * Returns the meta object for the containment reference '{@link de.tu_dortmund.mGPL.ForStmt#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see de.tu_dortmund.mGPL.ForStmt#getCondition()
   * @see #getForStmt()
   * @generated
   */
  EReference getForStmt_Condition();

  /**
   * Returns the meta object for the containment reference '{@link de.tu_dortmund.mGPL.ForStmt#getStep <em>Step</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Step</em>'.
   * @see de.tu_dortmund.mGPL.ForStmt#getStep()
   * @see #getForStmt()
   * @generated
   */
  EReference getForStmt_Step();

  /**
   * Returns the meta object for the containment reference '{@link de.tu_dortmund.mGPL.ForStmt#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Body</em>'.
   * @see de.tu_dortmund.mGPL.ForStmt#getBody()
   * @see #getForStmt()
   * @generated
   */
  EReference getForStmt_Body();

  /**
   * Returns the meta object for class '{@link de.tu_dortmund.mGPL.Assignment <em>Assignment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Assignment</em>'.
   * @see de.tu_dortmund.mGPL.Assignment
   * @generated
   */
  EClass getAssignment();

  /**
   * Returns the meta object for the containment reference '{@link de.tu_dortmund.mGPL.Assignment#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Var</em>'.
   * @see de.tu_dortmund.mGPL.Assignment#getVar()
   * @see #getAssignment()
   * @generated
   */
  EReference getAssignment_Var();

  /**
   * Returns the meta object for the containment reference '{@link de.tu_dortmund.mGPL.Assignment#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see de.tu_dortmund.mGPL.Assignment#getValue()
   * @see #getAssignment()
   * @generated
   */
  EReference getAssignment_Value();

  /**
   * Returns the meta object for class '{@link de.tu_dortmund.mGPL.AssStmt <em>Ass Stmt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ass Stmt</em>'.
   * @see de.tu_dortmund.mGPL.AssStmt
   * @generated
   */
  EClass getAssStmt();

  /**
   * Returns the meta object for class '{@link de.tu_dortmund.mGPL.Var <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Var</em>'.
   * @see de.tu_dortmund.mGPL.Var
   * @generated
   */
  EClass getVar();

  /**
   * Returns the meta object for the reference '{@link de.tu_dortmund.mGPL.Var#getVariable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Variable</em>'.
   * @see de.tu_dortmund.mGPL.Var#getVariable()
   * @see #getVar()
   * @generated
   */
  EReference getVar_Variable();

  /**
   * Returns the meta object for the containment reference '{@link de.tu_dortmund.mGPL.Var#getIndex <em>Index</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Index</em>'.
   * @see de.tu_dortmund.mGPL.Var#getIndex()
   * @see #getVar()
   * @generated
   */
  EReference getVar_Index();

  /**
   * Returns the meta object for the attribute '{@link de.tu_dortmund.mGPL.Var#getAttribute <em>Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Attribute</em>'.
   * @see de.tu_dortmund.mGPL.Var#getAttribute()
   * @see #getVar()
   * @generated
   */
  EAttribute getVar_Attribute();

  /**
   * Returns the meta object for class '{@link de.tu_dortmund.mGPL.Expr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expr</em>'.
   * @see de.tu_dortmund.mGPL.Expr
   * @generated
   */
  EClass getExpr();

  /**
   * Returns the meta object for class '{@link de.tu_dortmund.mGPL.UnaryExpr <em>Unary Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Unary Expr</em>'.
   * @see de.tu_dortmund.mGPL.UnaryExpr
   * @generated
   */
  EClass getUnaryExpr();

  /**
   * Returns the meta object for the attribute '{@link de.tu_dortmund.mGPL.UnaryExpr#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see de.tu_dortmund.mGPL.UnaryExpr#getOp()
   * @see #getUnaryExpr()
   * @generated
   */
  EAttribute getUnaryExpr_Op();

  /**
   * Returns the meta object for the containment reference '{@link de.tu_dortmund.mGPL.UnaryExpr#getOperand <em>Operand</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Operand</em>'.
   * @see de.tu_dortmund.mGPL.UnaryExpr#getOperand()
   * @see #getUnaryExpr()
   * @generated
   */
  EReference getUnaryExpr_Operand();

  /**
   * Returns the meta object for class '{@link de.tu_dortmund.mGPL.NumberExpr <em>Number Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Number Expr</em>'.
   * @see de.tu_dortmund.mGPL.NumberExpr
   * @generated
   */
  EClass getNumberExpr();

  /**
   * Returns the meta object for the attribute '{@link de.tu_dortmund.mGPL.NumberExpr#getNumber <em>Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Number</em>'.
   * @see de.tu_dortmund.mGPL.NumberExpr#getNumber()
   * @see #getNumberExpr()
   * @generated
   */
  EAttribute getNumberExpr_Number();

  /**
   * Returns the meta object for class '{@link de.tu_dortmund.mGPL.VarExpr <em>Var Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Var Expr</em>'.
   * @see de.tu_dortmund.mGPL.VarExpr
   * @generated
   */
  EClass getVarExpr();

  /**
   * Returns the meta object for the containment reference '{@link de.tu_dortmund.mGPL.VarExpr#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Var</em>'.
   * @see de.tu_dortmund.mGPL.VarExpr#getVar()
   * @see #getVarExpr()
   * @generated
   */
  EReference getVarExpr_Var();

  /**
   * Returns the meta object for class '{@link de.tu_dortmund.mGPL.BinaryExpr <em>Binary Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Binary Expr</em>'.
   * @see de.tu_dortmund.mGPL.BinaryExpr
   * @generated
   */
  EClass getBinaryExpr();

  /**
   * Returns the meta object for the containment reference '{@link de.tu_dortmund.mGPL.BinaryExpr#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see de.tu_dortmund.mGPL.BinaryExpr#getLeft()
   * @see #getBinaryExpr()
   * @generated
   */
  EReference getBinaryExpr_Left();

  /**
   * Returns the meta object for the attribute '{@link de.tu_dortmund.mGPL.BinaryExpr#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see de.tu_dortmund.mGPL.BinaryExpr#getOp()
   * @see #getBinaryExpr()
   * @generated
   */
  EAttribute getBinaryExpr_Op();

  /**
   * Returns the meta object for the containment reference '{@link de.tu_dortmund.mGPL.BinaryExpr#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see de.tu_dortmund.mGPL.BinaryExpr#getRight()
   * @see #getBinaryExpr()
   * @generated
   */
  EReference getBinaryExpr_Right();

  /**
   * Returns the meta object for class '{@link de.tu_dortmund.mGPL.TouchExpr <em>Touch Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Touch Expr</em>'.
   * @see de.tu_dortmund.mGPL.TouchExpr
   * @generated
   */
  EClass getTouchExpr();

  /**
   * Returns the meta object for the containment reference '{@link de.tu_dortmund.mGPL.TouchExpr#getToucher <em>Toucher</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Toucher</em>'.
   * @see de.tu_dortmund.mGPL.TouchExpr#getToucher()
   * @see #getTouchExpr()
   * @generated
   */
  EReference getTouchExpr_Toucher();

  /**
   * Returns the meta object for the containment reference '{@link de.tu_dortmund.mGPL.TouchExpr#getTouchee <em>Touchee</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Touchee</em>'.
   * @see de.tu_dortmund.mGPL.TouchExpr#getTouchee()
   * @see #getTouchExpr()
   * @generated
   */
  EReference getTouchExpr_Touchee();

  /**
   * Returns the meta object for enum '{@link de.tu_dortmund.mGPL.ObjType <em>Obj Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Obj Type</em>'.
   * @see de.tu_dortmund.mGPL.ObjType
   * @generated
   */
  EEnum getObjType();

  /**
   * Returns the meta object for enum '{@link de.tu_dortmund.mGPL.KeyStroke <em>Key Stroke</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Key Stroke</em>'.
   * @see de.tu_dortmund.mGPL.KeyStroke
   * @generated
   */
  EEnum getKeyStroke();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MGPLFactory getMGPLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link de.tu_dortmund.mGPL.impl.ProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.tu_dortmund.mGPL.impl.ProgramImpl
     * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getProgram()
     * @generated
     */
    EClass PROGRAM = eINSTANCE.getProgram();

    /**
     * The meta object literal for the '<em><b>Attributes</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__ATTRIBUTES = eINSTANCE.getProgram_Attributes();

    /**
     * The meta object literal for the '<em><b>Declarations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__DECLARATIONS = eINSTANCE.getProgram_Declarations();

    /**
     * The meta object literal for the '<em><b>Init</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__INIT = eINSTANCE.getProgram_Init();

    /**
     * The meta object literal for the '<em><b>Blocks</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__BLOCKS = eINSTANCE.getProgram_Blocks();

    /**
     * The meta object literal for the '{@link de.tu_dortmund.mGPL.impl.ReferenceTargetImpl <em>Reference Target</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.tu_dortmund.mGPL.impl.ReferenceTargetImpl
     * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getReferenceTarget()
     * @generated
     */
    EClass REFERENCE_TARGET = eINSTANCE.getReferenceTarget();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REFERENCE_TARGET__NAME = eINSTANCE.getReferenceTarget_Name();

    /**
     * The meta object literal for the '{@link de.tu_dortmund.mGPL.impl.DeclImpl <em>Decl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.tu_dortmund.mGPL.impl.DeclImpl
     * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getDecl()
     * @generated
     */
    EClass DECL = eINSTANCE.getDecl();

    /**
     * The meta object literal for the '{@link de.tu_dortmund.mGPL.impl.VarDeclImpl <em>Var Decl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.tu_dortmund.mGPL.impl.VarDeclImpl
     * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getVarDecl()
     * @generated
     */
    EClass VAR_DECL = eINSTANCE.getVarDecl();

    /**
     * The meta object literal for the '{@link de.tu_dortmund.mGPL.impl.ScalarVarDeclImpl <em>Scalar Var Decl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.tu_dortmund.mGPL.impl.ScalarVarDeclImpl
     * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getScalarVarDecl()
     * @generated
     */
    EClass SCALAR_VAR_DECL = eINSTANCE.getScalarVarDecl();

    /**
     * The meta object literal for the '<em><b>Initialization</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCALAR_VAR_DECL__INITIALIZATION = eINSTANCE.getScalarVarDecl_Initialization();

    /**
     * The meta object literal for the '{@link de.tu_dortmund.mGPL.impl.ArrayVarDeclImpl <em>Array Var Decl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.tu_dortmund.mGPL.impl.ArrayVarDeclImpl
     * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getArrayVarDecl()
     * @generated
     */
    EClass ARRAY_VAR_DECL = eINSTANCE.getArrayVarDecl();

    /**
     * The meta object literal for the '<em><b>Size</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ARRAY_VAR_DECL__SIZE = eINSTANCE.getArrayVarDecl_Size();

    /**
     * The meta object literal for the '{@link de.tu_dortmund.mGPL.impl.ObjDeclImpl <em>Obj Decl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.tu_dortmund.mGPL.impl.ObjDeclImpl
     * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getObjDecl()
     * @generated
     */
    EClass OBJ_DECL = eINSTANCE.getObjDecl();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJ_DECL__TYPE = eINSTANCE.getObjDecl_Type();

    /**
     * The meta object literal for the '<em><b>Attributes</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJ_DECL__ATTRIBUTES = eINSTANCE.getObjDecl_Attributes();

    /**
     * The meta object literal for the '{@link de.tu_dortmund.mGPL.impl.ObjArrayDeclImpl <em>Obj Array Decl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.tu_dortmund.mGPL.impl.ObjArrayDeclImpl
     * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getObjArrayDecl()
     * @generated
     */
    EClass OBJ_ARRAY_DECL = eINSTANCE.getObjArrayDecl();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJ_ARRAY_DECL__TYPE = eINSTANCE.getObjArrayDecl_Type();

    /**
     * The meta object literal for the '<em><b>Size</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJ_ARRAY_DECL__SIZE = eINSTANCE.getObjArrayDecl_Size();

    /**
     * The meta object literal for the '{@link de.tu_dortmund.mGPL.impl.AttrAssListImpl <em>Attr Ass List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.tu_dortmund.mGPL.impl.AttrAssListImpl
     * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getAttrAssList()
     * @generated
     */
    EClass ATTR_ASS_LIST = eINSTANCE.getAttrAssList();

    /**
     * The meta object literal for the '<em><b>Assignments</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTR_ASS_LIST__ASSIGNMENTS = eINSTANCE.getAttrAssList_Assignments();

    /**
     * The meta object literal for the '{@link de.tu_dortmund.mGPL.impl.AttrAssImpl <em>Attr Ass</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.tu_dortmund.mGPL.impl.AttrAssImpl
     * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getAttrAss()
     * @generated
     */
    EClass ATTR_ASS = eINSTANCE.getAttrAss();

    /**
     * The meta object literal for the '<em><b>Attribute Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTR_ASS__ATTRIBUTE_NAME = eINSTANCE.getAttrAss_AttributeName();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTR_ASS__VALUE = eINSTANCE.getAttrAss_Value();

    /**
     * The meta object literal for the '{@link de.tu_dortmund.mGPL.impl.BlockImpl <em>Block</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.tu_dortmund.mGPL.impl.BlockImpl
     * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getBlock()
     * @generated
     */
    EClass BLOCK = eINSTANCE.getBlock();

    /**
     * The meta object literal for the '<em><b>Action</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BLOCK__ACTION = eINSTANCE.getBlock_Action();

    /**
     * The meta object literal for the '{@link de.tu_dortmund.mGPL.impl.AnimBlockImpl <em>Anim Block</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.tu_dortmund.mGPL.impl.AnimBlockImpl
     * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getAnimBlock()
     * @generated
     */
    EClass ANIM_BLOCK = eINSTANCE.getAnimBlock();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ANIM_BLOCK__TARGET = eINSTANCE.getAnimBlock_Target();

    /**
     * The meta object literal for the '{@link de.tu_dortmund.mGPL.impl.AnimTargetImpl <em>Anim Target</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.tu_dortmund.mGPL.impl.AnimTargetImpl
     * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getAnimTarget()
     * @generated
     */
    EClass ANIM_TARGET = eINSTANCE.getAnimTarget();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ANIM_TARGET__TYPE = eINSTANCE.getAnimTarget_Type();

    /**
     * The meta object literal for the '{@link de.tu_dortmund.mGPL.impl.EventBlockImpl <em>Event Block</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.tu_dortmund.mGPL.impl.EventBlockImpl
     * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getEventBlock()
     * @generated
     */
    EClass EVENT_BLOCK = eINSTANCE.getEventBlock();

    /**
     * The meta object literal for the '<em><b>Key</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT_BLOCK__KEY = eINSTANCE.getEventBlock_Key();

    /**
     * The meta object literal for the '{@link de.tu_dortmund.mGPL.impl.StmtBlockImpl <em>Stmt Block</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.tu_dortmund.mGPL.impl.StmtBlockImpl
     * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getStmtBlock()
     * @generated
     */
    EClass STMT_BLOCK = eINSTANCE.getStmtBlock();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STMT_BLOCK__STATEMENTS = eINSTANCE.getStmtBlock_Statements();

    /**
     * The meta object literal for the '{@link de.tu_dortmund.mGPL.impl.StmtImpl <em>Stmt</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.tu_dortmund.mGPL.impl.StmtImpl
     * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getStmt()
     * @generated
     */
    EClass STMT = eINSTANCE.getStmt();

    /**
     * The meta object literal for the '{@link de.tu_dortmund.mGPL.impl.IfStmtImpl <em>If Stmt</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.tu_dortmund.mGPL.impl.IfStmtImpl
     * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getIfStmt()
     * @generated
     */
    EClass IF_STMT = eINSTANCE.getIfStmt();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF_STMT__CONDITION = eINSTANCE.getIfStmt_Condition();

    /**
     * The meta object literal for the '<em><b>Then</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF_STMT__THEN = eINSTANCE.getIfStmt_Then();

    /**
     * The meta object literal for the '<em><b>Else</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF_STMT__ELSE = eINSTANCE.getIfStmt_Else();

    /**
     * The meta object literal for the '{@link de.tu_dortmund.mGPL.impl.ForStmtImpl <em>For Stmt</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.tu_dortmund.mGPL.impl.ForStmtImpl
     * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getForStmt()
     * @generated
     */
    EClass FOR_STMT = eINSTANCE.getForStmt();

    /**
     * The meta object literal for the '<em><b>Init</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR_STMT__INIT = eINSTANCE.getForStmt_Init();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR_STMT__CONDITION = eINSTANCE.getForStmt_Condition();

    /**
     * The meta object literal for the '<em><b>Step</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR_STMT__STEP = eINSTANCE.getForStmt_Step();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR_STMT__BODY = eINSTANCE.getForStmt_Body();

    /**
     * The meta object literal for the '{@link de.tu_dortmund.mGPL.impl.AssignmentImpl <em>Assignment</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.tu_dortmund.mGPL.impl.AssignmentImpl
     * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getAssignment()
     * @generated
     */
    EClass ASSIGNMENT = eINSTANCE.getAssignment();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSIGNMENT__VAR = eINSTANCE.getAssignment_Var();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSIGNMENT__VALUE = eINSTANCE.getAssignment_Value();

    /**
     * The meta object literal for the '{@link de.tu_dortmund.mGPL.impl.AssStmtImpl <em>Ass Stmt</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.tu_dortmund.mGPL.impl.AssStmtImpl
     * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getAssStmt()
     * @generated
     */
    EClass ASS_STMT = eINSTANCE.getAssStmt();

    /**
     * The meta object literal for the '{@link de.tu_dortmund.mGPL.impl.VarImpl <em>Var</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.tu_dortmund.mGPL.impl.VarImpl
     * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getVar()
     * @generated
     */
    EClass VAR = eINSTANCE.getVar();

    /**
     * The meta object literal for the '<em><b>Variable</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VAR__VARIABLE = eINSTANCE.getVar_Variable();

    /**
     * The meta object literal for the '<em><b>Index</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VAR__INDEX = eINSTANCE.getVar_Index();

    /**
     * The meta object literal for the '<em><b>Attribute</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VAR__ATTRIBUTE = eINSTANCE.getVar_Attribute();

    /**
     * The meta object literal for the '{@link de.tu_dortmund.mGPL.impl.ExprImpl <em>Expr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.tu_dortmund.mGPL.impl.ExprImpl
     * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getExpr()
     * @generated
     */
    EClass EXPR = eINSTANCE.getExpr();

    /**
     * The meta object literal for the '{@link de.tu_dortmund.mGPL.impl.UnaryExprImpl <em>Unary Expr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.tu_dortmund.mGPL.impl.UnaryExprImpl
     * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getUnaryExpr()
     * @generated
     */
    EClass UNARY_EXPR = eINSTANCE.getUnaryExpr();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNARY_EXPR__OP = eINSTANCE.getUnaryExpr_Op();

    /**
     * The meta object literal for the '<em><b>Operand</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UNARY_EXPR__OPERAND = eINSTANCE.getUnaryExpr_Operand();

    /**
     * The meta object literal for the '{@link de.tu_dortmund.mGPL.impl.NumberExprImpl <em>Number Expr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.tu_dortmund.mGPL.impl.NumberExprImpl
     * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getNumberExpr()
     * @generated
     */
    EClass NUMBER_EXPR = eINSTANCE.getNumberExpr();

    /**
     * The meta object literal for the '<em><b>Number</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NUMBER_EXPR__NUMBER = eINSTANCE.getNumberExpr_Number();

    /**
     * The meta object literal for the '{@link de.tu_dortmund.mGPL.impl.VarExprImpl <em>Var Expr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.tu_dortmund.mGPL.impl.VarExprImpl
     * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getVarExpr()
     * @generated
     */
    EClass VAR_EXPR = eINSTANCE.getVarExpr();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VAR_EXPR__VAR = eINSTANCE.getVarExpr_Var();

    /**
     * The meta object literal for the '{@link de.tu_dortmund.mGPL.impl.BinaryExprImpl <em>Binary Expr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.tu_dortmund.mGPL.impl.BinaryExprImpl
     * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getBinaryExpr()
     * @generated
     */
    EClass BINARY_EXPR = eINSTANCE.getBinaryExpr();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BINARY_EXPR__LEFT = eINSTANCE.getBinaryExpr_Left();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BINARY_EXPR__OP = eINSTANCE.getBinaryExpr_Op();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BINARY_EXPR__RIGHT = eINSTANCE.getBinaryExpr_Right();

    /**
     * The meta object literal for the '{@link de.tu_dortmund.mGPL.impl.TouchExprImpl <em>Touch Expr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.tu_dortmund.mGPL.impl.TouchExprImpl
     * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getTouchExpr()
     * @generated
     */
    EClass TOUCH_EXPR = eINSTANCE.getTouchExpr();

    /**
     * The meta object literal for the '<em><b>Toucher</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TOUCH_EXPR__TOUCHER = eINSTANCE.getTouchExpr_Toucher();

    /**
     * The meta object literal for the '<em><b>Touchee</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TOUCH_EXPR__TOUCHEE = eINSTANCE.getTouchExpr_Touchee();

    /**
     * The meta object literal for the '{@link de.tu_dortmund.mGPL.ObjType <em>Obj Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.tu_dortmund.mGPL.ObjType
     * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getObjType()
     * @generated
     */
    EEnum OBJ_TYPE = eINSTANCE.getObjType();

    /**
     * The meta object literal for the '{@link de.tu_dortmund.mGPL.KeyStroke <em>Key Stroke</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.tu_dortmund.mGPL.KeyStroke
     * @see de.tu_dortmund.mGPL.impl.MGPLPackageImpl#getKeyStroke()
     * @generated
     */
    EEnum KEY_STROKE = eINSTANCE.getKeyStroke();

  }

} //MGPLPackage
