/**
 * generated by Xtext 2.20.0
 */
package de.tu_dortmund.mGPL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Obj Decl</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.tu_dortmund.mGPL.ObjDecl#getType <em>Type</em>}</li>
 *   <li>{@link de.tu_dortmund.mGPL.ObjDecl#getAttributes <em>Attributes</em>}</li>
 * </ul>
 *
 * @see de.tu_dortmund.mGPL.MGPLPackage#getObjDecl()
 * @model
 * @generated
 */
public interface ObjDecl extends Decl
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link de.tu_dortmund.mGPL.ObjType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see de.tu_dortmund.mGPL.ObjType
   * @see #setType(ObjType)
   * @see de.tu_dortmund.mGPL.MGPLPackage#getObjDecl_Type()
   * @model
   * @generated
   */
  ObjType getType();

  /**
   * Sets the value of the '{@link de.tu_dortmund.mGPL.ObjDecl#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see de.tu_dortmund.mGPL.ObjType
   * @see #getType()
   * @generated
   */
  void setType(ObjType value);

  /**
   * Returns the value of the '<em><b>Attributes</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attributes</em>' containment reference.
   * @see #setAttributes(AttrAssList)
   * @see de.tu_dortmund.mGPL.MGPLPackage#getObjDecl_Attributes()
   * @model containment="true"
   * @generated
   */
  AttrAssList getAttributes();

  /**
   * Sets the value of the '{@link de.tu_dortmund.mGPL.ObjDecl#getAttributes <em>Attributes</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attributes</em>' containment reference.
   * @see #getAttributes()
   * @generated
   */
  void setAttributes(AttrAssList value);

} // ObjDecl
