/**
 * generated by Xtext 2.20.0
 */
package de.tu_dortmund.mGPL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Scalar Var Decl</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.tu_dortmund.mGPL.ScalarVarDecl#getInitialization <em>Initialization</em>}</li>
 * </ul>
 *
 * @see de.tu_dortmund.mGPL.MGPLPackage#getScalarVarDecl()
 * @model
 * @generated
 */
public interface ScalarVarDecl extends VarDecl
{
  /**
   * Returns the value of the '<em><b>Initialization</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Initialization</em>' containment reference.
   * @see #setInitialization(Expr)
   * @see de.tu_dortmund.mGPL.MGPLPackage#getScalarVarDecl_Initialization()
   * @model containment="true"
   * @generated
   */
  Expr getInitialization();

  /**
   * Sets the value of the '{@link de.tu_dortmund.mGPL.ScalarVarDecl#getInitialization <em>Initialization</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Initialization</em>' containment reference.
   * @see #getInitialization()
   * @generated
   */
  void setInitialization(Expr value);

} // ScalarVarDecl
