/**
 * generated by Xtext 2.20.0
 */
package de.tu_dortmund.mGPL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Touch Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.tu_dortmund.mGPL.TouchExpr#getToucher <em>Toucher</em>}</li>
 *   <li>{@link de.tu_dortmund.mGPL.TouchExpr#getTouchee <em>Touchee</em>}</li>
 * </ul>
 *
 * @see de.tu_dortmund.mGPL.MGPLPackage#getTouchExpr()
 * @model
 * @generated
 */
public interface TouchExpr extends Expr
{
  /**
   * Returns the value of the '<em><b>Toucher</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Toucher</em>' containment reference.
   * @see #setToucher(VarExpr)
   * @see de.tu_dortmund.mGPL.MGPLPackage#getTouchExpr_Toucher()
   * @model containment="true"
   * @generated
   */
  VarExpr getToucher();

  /**
   * Sets the value of the '{@link de.tu_dortmund.mGPL.TouchExpr#getToucher <em>Toucher</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Toucher</em>' containment reference.
   * @see #getToucher()
   * @generated
   */
  void setToucher(VarExpr value);

  /**
   * Returns the value of the '<em><b>Touchee</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Touchee</em>' containment reference.
   * @see #setTouchee(VarExpr)
   * @see de.tu_dortmund.mGPL.MGPLPackage#getTouchExpr_Touchee()
   * @model containment="true"
   * @generated
   */
  VarExpr getTouchee();

  /**
   * Sets the value of the '{@link de.tu_dortmund.mGPL.TouchExpr#getTouchee <em>Touchee</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Touchee</em>' containment reference.
   * @see #getTouchee()
   * @generated
   */
  void setTouchee(VarExpr value);

} // TouchExpr
