/*
 * generated by Xtext 2.20.0
 */
package de.tu_dortmund.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMGPLScopeProvider extends DelegatingScopeProvider {
}
