/*
 * generated by Xtext 2.20.0
 */
package de.tu_dortmund.serializer;

import com.google.inject.Inject;
import de.tu_dortmund.services.MGPLGrammarAccess;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class MGPLSyntacticSequencer extends AbstractSyntacticSequencer {

	protected MGPLGrammarAccess grammarAccess;
	protected AbstractElementAlias match_SimpleExpr_LeftParenthesisKeyword_3_0_a;
	protected AbstractElementAlias match_SimpleExpr_LeftParenthesisKeyword_3_0_p;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (MGPLGrammarAccess) access;
		match_SimpleExpr_LeftParenthesisKeyword_3_0_a = new TokenAlias(true, true, grammarAccess.getSimpleExprAccess().getLeftParenthesisKeyword_3_0());
		match_SimpleExpr_LeftParenthesisKeyword_3_0_p = new TokenAlias(true, false, grammarAccess.getSimpleExprAccess().getLeftParenthesisKeyword_3_0());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_SimpleExpr_LeftParenthesisKeyword_3_0_a.equals(syntax))
				emit_SimpleExpr_LeftParenthesisKeyword_3_0_a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_SimpleExpr_LeftParenthesisKeyword_3_0_p.equals(syntax))
				emit_SimpleExpr_LeftParenthesisKeyword_3_0_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     '('*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) number=INT
	 *     (rule start) (ambiguity) op='!'
	 *     (rule start) (ambiguity) op='-'
	 *     (rule start) (ambiguity) var=Var
	 *     (rule start) (ambiguity) {BinaryExpr.left=}
	 *     (rule start) (ambiguity) {TouchExpr.toucher=}
	 */
	protected void emit_SimpleExpr_LeftParenthesisKeyword_3_0_a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '('+
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) {BinaryExpr.left=}
	 */
	protected void emit_SimpleExpr_LeftParenthesisKeyword_3_0_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
