/*
 * generated by Xtext 2.20.0
 */
package de.tu_dortmund.parser.antlr;

import com.google.inject.Inject;
import de.tu_dortmund.parser.antlr.internal.InternalMGPLParser;
import de.tu_dortmund.services.MGPLGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class MGPLParser extends AbstractAntlrParser {

	@Inject
	private MGPLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMGPLParser createParser(XtextTokenStream stream) {
		return new InternalMGPLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}

	public MGPLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MGPLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
