/*
 * generated by Xtext 2.20.0
 */
package de.tu_dortmund.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MGPLUiModule extends AbstractMGPLUiModule {

	public MGPLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
