/*
 * generated by Xtext 2.20.0
 */
package de.tu_dortmund.ui;

import com.google.inject.Injector;
import de.tu_dortmund.mgpl.ui.internal.MgplActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MGPLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(MgplActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		MgplActivator activator = MgplActivator.getInstance();
		return activator != null ? activator.getInjector(MgplActivator.DE_TU_DORTMUND_MGPL) : null;
	}

}
