/*
 * generated by Xtext 2.20.0
 */
package de.tu_dortmund;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MGPLRuntimeModule extends AbstractMGPLRuntimeModule {
}
